### ISSUE TITLE
Running Tests for challenges

### ISSUE THREAD

**Issue by prasmaran** [igorwojda/kotlin-coding-challenges#109]
I am trying to figure out how to run the test cases for each challenge as I am not seeing the green play icon near the test classes

![image](https://user-images.githubusercontent.com/78822062/228034266-8797252a-385c-4401-942f-cf5380d59ca7.png)

![image](https://user-images.githubusercontent.com/78822062/228034693-0f63edbb-a9e6-4e0b-a6b2-10a7f4f5e2d7.png)

Please guide me on this matter, thanks a lot!

**Comment by Arrowsome** [comment]
Open `Settings > Build, Execution, Deployment > Build tools > Gradle` and set `Gradle JVM` to a version `17` or lower.

![image](https://github.com/igorwojda/kotlin-coding-challenges/assets/61705762/70941ac2-c1e4-4e06-8682-caa5aaef0417)

**Comment by igorwojda** [comment]
I have added `Troubleshoot` section to the main README
 https://[github.com/igorwojda/kotlin-coding-challenges/commit/4f5cc523ad58472f4416ce285725823478dc3fa7](https://github.com/igorwojda/kotlin-coding-challenges/commit/4f5cc523ad58472f4416ce285725823478dc3fa7)
