### ISSUE TITLE
Error in solution for Queue with Linked List based implementation

### ISSUE THREAD

**Issue by ivaleev1997** [igorwojda/kotlin-coding-challenges#26]
Method `remove()` hasn't validate first node is null  or size is 0 before decrease size. So size value may be less than zero if you invoke remove with empty queue.
```kotlin
        fun remove(): E? {
            val node = first
            first = node?.next
            size--
            return node?.data
        }
```

**Comment by igorwojda** [comment]
merci

Fixed by https://github.com/igorwojda/kotlin-coding-challenges/commit/530f48b11c5fd39322c5abd10dbcae0b7b42d284
